/**
 * generated by Xtext 2.40.0
 */
package org.farhan.dsl.asciidoc.asciiDoc.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.farhan.dsl.asciidoc.asciiDoc.AsciiDocPackage;
import org.farhan.dsl.asciidoc.asciiDoc.Description;
import org.farhan.dsl.asciidoc.asciiDoc.StepDefinition;
import org.farhan.dsl.asciidoc.asciiDoc.StepParameters;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Step Definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.farhan.dsl.asciidoc.asciiDoc.impl.StepDefinitionImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.farhan.dsl.asciidoc.asciiDoc.impl.StepDefinitionImpl#getDescription <em>Description</em>}</li>
 *   <li>{@link org.farhan.dsl.asciidoc.asciiDoc.impl.StepDefinitionImpl#getStepParameterList <em>Step Parameter List</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StepDefinitionImpl extends MinimalEObjectImpl.Container implements StepDefinition
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected Description description;

  /**
   * The cached value of the '{@link #getStepParameterList() <em>Step Parameter List</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStepParameterList()
   * @generated
   * @ordered
   */
  protected EList<StepParameters> stepParameterList;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StepDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsciiDocPackage.Literals.STEP_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AsciiDocPackage.STEP_DEFINITION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Description getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDescription(Description newDescription, NotificationChain msgs)
  {
    Description oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AsciiDocPackage.STEP_DEFINITION__DESCRIPTION, oldDescription, newDescription);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescription(Description newDescription)
  {
    if (newDescription != description)
    {
      NotificationChain msgs = null;
      if (description != null)
        msgs = ((InternalEObject)description).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AsciiDocPackage.STEP_DEFINITION__DESCRIPTION, null, msgs);
      if (newDescription != null)
        msgs = ((InternalEObject)newDescription).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AsciiDocPackage.STEP_DEFINITION__DESCRIPTION, null, msgs);
      msgs = basicSetDescription(newDescription, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AsciiDocPackage.STEP_DEFINITION__DESCRIPTION, newDescription, newDescription));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<StepParameters> getStepParameterList()
  {
    if (stepParameterList == null)
    {
      stepParameterList = new EObjectContainmentEList<StepParameters>(StepParameters.class, this, AsciiDocPackage.STEP_DEFINITION__STEP_PARAMETER_LIST);
    }
    return stepParameterList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AsciiDocPackage.STEP_DEFINITION__DESCRIPTION:
        return basicSetDescription(null, msgs);
      case AsciiDocPackage.STEP_DEFINITION__STEP_PARAMETER_LIST:
        return ((InternalEList<?>)getStepParameterList()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AsciiDocPackage.STEP_DEFINITION__NAME:
        return getName();
      case AsciiDocPackage.STEP_DEFINITION__DESCRIPTION:
        return getDescription();
      case AsciiDocPackage.STEP_DEFINITION__STEP_PARAMETER_LIST:
        return getStepParameterList();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AsciiDocPackage.STEP_DEFINITION__NAME:
        setName((String)newValue);
        return;
      case AsciiDocPackage.STEP_DEFINITION__DESCRIPTION:
        setDescription((Description)newValue);
        return;
      case AsciiDocPackage.STEP_DEFINITION__STEP_PARAMETER_LIST:
        getStepParameterList().clear();
        getStepParameterList().addAll((Collection<? extends StepParameters>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AsciiDocPackage.STEP_DEFINITION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case AsciiDocPackage.STEP_DEFINITION__DESCRIPTION:
        setDescription((Description)null);
        return;
      case AsciiDocPackage.STEP_DEFINITION__STEP_PARAMETER_LIST:
        getStepParameterList().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AsciiDocPackage.STEP_DEFINITION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case AsciiDocPackage.STEP_DEFINITION__DESCRIPTION:
        return description != null;
      case AsciiDocPackage.STEP_DEFINITION__STEP_PARAMETER_LIST:
        return stepParameterList != null && !stepParameterList.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //StepDefinitionImpl
