/**
 * generated by Xtext 2.40.0
 */
package org.farhan.dsl.asciidoc.asciiDoc.impl;

import org.eclipse.emf.ecore.EClass;

import org.farhan.dsl.asciidoc.asciiDoc.AsciiDocPackage;
import org.farhan.dsl.asciidoc.asciiDoc.TestSetup;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Test Setup</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TestSetupImpl extends TestStepContainerImpl implements TestSetup
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TestSetupImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsciiDocPackage.Literals.TEST_SETUP;
  }

} //TestSetupImpl
