/*
 * generated by Xtext 2.36.0
 */
package org.farhan.dsl.asciidoc.generator;

import java.io.File;
import java.util.ArrayList;
import org.eclipse.emf.ecore.resource.Resource;
import org.slf4j.Logger;
import org.farhan.dsl.grammar.SheepDogLoggerFactory;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.farhan.dsl.asciidoc.asciiDoc.TestStepContainer;
import org.farhan.dsl.asciidoc.asciiDoc.TestSuite;
import org.farhan.dsl.asciidoc.impl.RowImpl;
import org.farhan.dsl.asciidoc.impl.TestProjectImpl;
import org.farhan.dsl.asciidoc.impl.TestStepImpl;
import org.farhan.dsl.asciidoc.impl.TextImpl;
import org.farhan.dsl.issues.RowIssueDetector;
import org.farhan.dsl.issues.RowIssueResolver;
import org.farhan.dsl.issues.TestStepIssueDetector;
import org.farhan.dsl.issues.TestStepIssueResolver;
import org.farhan.dsl.issues.TextIssueDetector;
import org.farhan.dsl.issues.TextIssueResolver;
import org.farhan.dsl.grammar.SheepDogIssueProposal;
import org.farhan.dsl.grammar.IStepObject;
import org.farhan.dsl.grammar.ITestProject;
import org.farhan.dsl.grammar.SheepDogBuilder;
import org.farhan.dsl.asciidoc.asciiDoc.TestStep;

/**
 * Generates code from your model files on save.
 * 
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
public class AsciiDocGenerator extends AbstractGenerator {

	private static final Logger logger = SheepDogLoggerFactory.getLogger(AsciiDocGenerator.class);
	private static ITestProject testProject;

	@Override
	public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
		logger.debug("Entering doGenerate for resource: {}", resource != null ? resource.getURI() : "null");
		// Automatic generation disabled - use AsciiDocGeneratorCommandService
		// command-based generation instead so that code generation can be triggered
		// on-demand.
		logger.debug("Exiting {}", "doGenerate");
	}

	public static void generateFromResource(final Resource resource) {
		logger.info("Entering generateFromResource for resource: {}", resource != null ? resource.getURI() : "null");
		try {
			if (resource == null || resource.getContents().isEmpty()) {
				logger.warn("Resource is null or has no contents");
				return;
			}

			if (resource.getContents().get(0) instanceof TestSuite) {
				initProject(resource);
				TestSuite theTestSuite = (TestSuite) resource.getContents().get(0);
				logger.debug("Processing TestSuite: {}", theTestSuite.getName());

				for (TestStepContainer scenario : theTestSuite.getTestStepContainerList()) {
					logger.debug("Processing scenario: {}", scenario.getName());
					for (TestStep step : scenario.getTestStepList()) {
						try {
							TestStepImpl testStep = new TestStepImpl(step);
							logger.debug("Processing step: {} {}", testStep.getStepObjectName(), testStep.getStepDefinitionName());

							if (!TestStepIssueDetector.validateStepObjectNameWorkspace(testStep).isEmpty()) {
								applyProposal(TestStepIssueResolver.correctStepObjectNameWorkspace(testStep));
							}
							if (!TestStepIssueDetector.validateStepDefinitionNameWorkspace(testStep).isEmpty()) {
								applyProposal(TestStepIssueResolver.correctStepDefinitionNameWorkspace(testStep));
							}
							if (step.getTable() != null) {
								if (!step.getTable().getRowList().isEmpty()
										&& step.getTable().getRowList().getFirst() != null) {
									if (!RowIssueDetector
											.validateCellListWorkspace(new RowImpl(step.getTable().getRowList().getFirst()))
											.isEmpty()) {
										applyProposal(RowIssueResolver.correctCellListWorkspace(new TestStepImpl(step)));
									}
								}
							}
							if (step.getText() != null) {
								if (!TextIssueDetector.validateNameWorkspace(new TextImpl(step.getText())).isEmpty()) {
									applyProposal(TextIssueResolver.correctNameWorkspace(new TestStepImpl(step)));
								}
							}
						} catch (Exception e) {
							logger.error("Failed to process step: {}", e.getMessage(), e);
						}
					}
				}
			} else {
				logger.warn("Resource content is not a TestSuite: {}", resource.getContents().get(0).getClass());
			}
			logger.debug("Exiting {}", "generateFromResource");
		} catch (Exception e) {
			logger.error("Failed to generate from resource {}: {}", resource != null ? resource.getURI() : "null",
					e.getMessage(), e);
		}
	}

	private static void applyProposal(ArrayList<SheepDogIssueProposal> proposals) throws Exception {
		for (SheepDogIssueProposal p : proposals) {
			if (p.getValue() instanceof IStepObject) {
				((TestProjectImpl) testProject).addStepObject((IStepObject) p.getValue());
			}
		}
	}

	private static void initProject(Resource resource) {
		testProject = SheepDogBuilder.createTestProject();
		String resourcePath = resource.getURI().toFileString().replace(File.separator, "/");
		String projectPath = resourcePath.split("src/test/resources/asciidoc/specs/")[0].replace("/",
				File.separator);
		testProject.setName(new File(projectPath).getAbsolutePath());
	}

}
