/*
 * generated by Xtext 2.40.0
 */
package org.farhan.dsl.asciidoc.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.farhan.dsl.asciidoc.parser.antlr.internal.InternalAsciiDocParser;
import org.farhan.dsl.asciidoc.services.AsciiDocGrammarAccess;

public class AsciiDocParser extends AbstractAntlrParser {

	@Inject
	private AsciiDocGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAsciiDocParser createParser(XtextTokenStream stream) {
		return new InternalAsciiDocParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public AsciiDocGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AsciiDocGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
