/*
 * generated by Xtext 2.32.0
 */
package org.farhan.dsl.asciidoc.tests.parsing;

import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.farhan.dsl.asciidoc.tests.AsciiDocInjectorProvider;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(AsciiDocInjectorProvider.class)
public class SheepDogParsingTest extends ParsingTest {

	@Test
	public void parseCompleteFile() throws Exception {
		StringBuilder sb = new StringBuilder();
		sb.append("= Test-Suite: This is a test feature\n");
		sb.append("\n");
		sb.append("This is the description\n");
		sb.append("This is the second line of the description\n");
		sb.append("\n");

		sb.append("== Test-Setup: Setup a cardholder\n");
		sb.append("\n");
		sb.append("First setup a group\n");
		sb.append("Next setup the cardholder\n");
		sb.append("Next setup their family\n");
		sb.append("\n");

		sb.append("=== Given: The one service, one file is valid\n");
		sb.append("----\n");
		sb.append("Line1\n");
		sb.append("Line2\n");
		sb.append("Line3\n");
		sb.append("----\n");

		sb.append("=== And: The two service, two file is valid\n");

		sb.append("|===\n");
		sb.append("| Header1 | Header2 \n");
		sb.append("|   data1 |   data2 \n");
		sb.append("|===\n");

		sb.append("=== When: The three service, three file is valid\n");

		sb.append("|===\n");
		sb.append("| Header1 | Header2 \n");
		sb.append("|   data1 |   data2 \n");
		sb.append("|===\n");

		sb.append("=== Then: The four service, four file is valid\n");

		sb.append("|===\n");
		sb.append("| Header1 | Header2 \n");
		sb.append("|   data1 |   data2 \n");
		sb.append("|===\n");
		sb.append("\n");

		sb.append("== Test-Case: Submit a claim\n");
		sb.append("@tag1,@tag2,@tag3\n");
		sb.append("\n");
		sb.append("=== And: The two service, two file is valid\n");
		sb.append("\n");

		sb.append("== Test-Case: Submit a drug claim\n");
		sb.append("@tag1,@tag2,@tag3\n");
		sb.append("\n");
		sb.append("=== And: The two service, two file is valid\n");
		sb.append("=== When: The three service, three file is valid\n");
		sb.append("=== Then: The four service, four file is valid\n");
		sb.append("=== Given: The six service, six file is valid\n");
		sb.append("----\n");
		sb.append(" Line1\n");
		sb.append(" Line2 \n");
		sb.append("Line3 \n");
		sb.append("----\n");
		sb.append("\n");
		sb.append("== Test-Case: Submit a dental claim\n");
		sb.append("@tag1,@tag2,@tag3\n");
		sb.append("\n");
		sb.append("=== Given: The one service, one file is valid\n");
		sb.append("=== And: The two service, two file is valid\n");
		sb.append("|===\n");
		sb.append("| Header1 | Header2 \n");
		sb.append("|   data1 |   data2 \n");
		sb.append("|===\n");
		sb.append("=== When: The three service, three file is valid\n");
		sb.append("=== Then: The four service, four file is valid\n");
		sb.append("\n");
		sb.append("=== Test-Data: Describe what this data is about\n");
		sb.append("\n");
		sb.append("@tag1,@tag2,@tag3\n");
		sb.append("Put some explanation here.\n");
		sb.append("\n");
		sb.append("|===\n");
		sb.append("| Header1 | Header2 \n");
		sb.append("|   data1 |   data2 \n");
		sb.append("|   data3 |   data4 \n");
		sb.append("|===\n");
		sb.append("\n");
		sb.append("==  Test-Case: Submit a dental claim\n");
		sb.append("@tag1,@tag2,@tag3\n");
		sb.append("\n");
		sb.append("=== Given: The one service, one file is valid\n");
		sb.append("=== And: The two service, two file is valid\n");
		sb.append("=== When: The three service, three file is valid\n");
		sb.append("=== Then: The four service, four file is valid\n");
		sb.append("\n");
		sb.append("=== Test-Data: Describe what this data is about as well\n");
		sb.append("\n");
		sb.append("@tag1,@tag2,@tag3\n");
		sb.append("Put some explanation here.\n");
		sb.append("\n");
		sb.append("|===\n");
		sb.append("| Header1 | Header2 \n");
		sb.append("|   data1 |   data2 \n");
		sb.append("|   data3 |   data4 \n");
		sb.append("|===\n");
		sb.append("\n");
		sb.append("=== Test-Data: Describe this data too\n");
		sb.append("@tag1,@tag2,@tag3\n");
		sb.append("|===\n");
		sb.append("| Header1 | Header2 \n");
		sb.append("|   data1 |   data2 \n");
		sb.append("|===\n");

		sb.append("\n");
		sb.append("");
		assertNoFeatureErrors(sb);
	}

}
