/**
 * generated by Xtext 2.40.0
 */
package org.farhan.dsl.asciidoc.asciiDoc;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Test Setup</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.farhan.dsl.asciidoc.asciiDoc.AsciiDocPackage#getTestSetup()
 * @model
 * @generated
 */
public interface TestSetup extends TestStepContainer
{
} // TestSetup
