/**
 * generated by Xtext 2.40.0
 */
package org.farhan.dsl.asciidoc.asciiDoc;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.farhan.dsl.asciidoc.asciiDoc.AsciiDocFactory
 * @model kind="package"
 * @generated
 */
public interface AsciiDocPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "asciiDoc";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.farhan.org/dsl/asciidoc/AsciiDoc";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "asciiDoc";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AsciiDocPackage eINSTANCE = org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl.init();

  /**
   * The meta object id for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.ModelImpl
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__DESCRIPTION = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.StepObjectImpl <em>Step Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.StepObjectImpl
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getStepObject()
   * @generated
   */
  int STEP_OBJECT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_OBJECT__NAME = MODEL__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_OBJECT__DESCRIPTION = MODEL__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Step Definition List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_OBJECT__STEP_DEFINITION_LIST = MODEL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Step Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_OBJECT_FEATURE_COUNT = MODEL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.StepDefinitionImpl <em>Step Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.StepDefinitionImpl
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getStepDefinition()
   * @generated
   */
  int STEP_DEFINITION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_DEFINITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_DEFINITION__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Step Parameter List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_DEFINITION__STEP_PARAMETER_LIST = 2;

  /**
   * The number of structural features of the '<em>Step Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_DEFINITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.StepParametersImpl <em>Step Parameters</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.StepParametersImpl
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getStepParameters()
   * @generated
   */
  int STEP_PARAMETERS = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_PARAMETERS__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_PARAMETERS__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_PARAMETERS__TABLE = 2;

  /**
   * The number of structural features of the '<em>Step Parameters</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_PARAMETERS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.TestSuiteImpl <em>Test Suite</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.TestSuiteImpl
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getTestSuite()
   * @generated
   */
  int TEST_SUITE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SUITE__NAME = MODEL__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SUITE__DESCRIPTION = MODEL__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Test Step Container List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SUITE__TEST_STEP_CONTAINER_LIST = MODEL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Test Suite</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SUITE_FEATURE_COUNT = MODEL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.TestStepContainerImpl <em>Test Step Container</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.TestStepContainerImpl
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getTestStepContainer()
   * @generated
   */
  int TEST_STEP_CONTAINER = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_STEP_CONTAINER__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_STEP_CONTAINER__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Test Step List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_STEP_CONTAINER__TEST_STEP_LIST = 2;

  /**
   * The number of structural features of the '<em>Test Step Container</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_STEP_CONTAINER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.TestSetupImpl <em>Test Setup</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.TestSetupImpl
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getTestSetup()
   * @generated
   */
  int TEST_SETUP = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SETUP__NAME = TEST_STEP_CONTAINER__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SETUP__DESCRIPTION = TEST_STEP_CONTAINER__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Test Step List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SETUP__TEST_STEP_LIST = TEST_STEP_CONTAINER__TEST_STEP_LIST;

  /**
   * The number of structural features of the '<em>Test Setup</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SETUP_FEATURE_COUNT = TEST_STEP_CONTAINER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.TestCaseImpl <em>Test Case</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.TestCaseImpl
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getTestCase()
   * @generated
   */
  int TEST_CASE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE__NAME = TEST_STEP_CONTAINER__NAME;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE__DESCRIPTION = TEST_STEP_CONTAINER__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Test Step List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE__TEST_STEP_LIST = TEST_STEP_CONTAINER__TEST_STEP_LIST;

  /**
   * The feature id for the '<em><b>Test Data List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE__TEST_DATA_LIST = TEST_STEP_CONTAINER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Test Case</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE_FEATURE_COUNT = TEST_STEP_CONTAINER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.TestDataImpl <em>Test Data</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.TestDataImpl
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getTestData()
   * @generated
   */
  int TEST_DATA = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_DATA__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_DATA__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_DATA__TABLE = 2;

  /**
   * The number of structural features of the '<em>Test Data</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_DATA_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.TestStepImpl <em>Test Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.TestStepImpl
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getTestStep()
   * @generated
   */
  int TEST_STEP = 9;

  /**
   * The feature id for the '<em><b>Step Object Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_STEP__STEP_OBJECT_NAME = 0;

  /**
   * The feature id for the '<em><b>Step Definition Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_STEP__STEP_DEFINITION_NAME = 1;

  /**
   * The feature id for the '<em><b>Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_STEP__TABLE = 2;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_STEP__TEXT = 3;

  /**
   * The number of structural features of the '<em>Test Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_STEP_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.GivenImpl <em>Given</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.GivenImpl
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getGiven()
   * @generated
   */
  int GIVEN = 10;

  /**
   * The feature id for the '<em><b>Step Object Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GIVEN__STEP_OBJECT_NAME = TEST_STEP__STEP_OBJECT_NAME;

  /**
   * The feature id for the '<em><b>Step Definition Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GIVEN__STEP_DEFINITION_NAME = TEST_STEP__STEP_DEFINITION_NAME;

  /**
   * The feature id for the '<em><b>Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GIVEN__TABLE = TEST_STEP__TABLE;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GIVEN__TEXT = TEST_STEP__TEXT;

  /**
   * The number of structural features of the '<em>Given</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GIVEN_FEATURE_COUNT = TEST_STEP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.WhenImpl <em>When</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.WhenImpl
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getWhen()
   * @generated
   */
  int WHEN = 11;

  /**
   * The feature id for the '<em><b>Step Object Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN__STEP_OBJECT_NAME = TEST_STEP__STEP_OBJECT_NAME;

  /**
   * The feature id for the '<em><b>Step Definition Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN__STEP_DEFINITION_NAME = TEST_STEP__STEP_DEFINITION_NAME;

  /**
   * The feature id for the '<em><b>Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN__TABLE = TEST_STEP__TABLE;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN__TEXT = TEST_STEP__TEXT;

  /**
   * The number of structural features of the '<em>When</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN_FEATURE_COUNT = TEST_STEP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.ThenImpl <em>Then</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.ThenImpl
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getThen()
   * @generated
   */
  int THEN = 12;

  /**
   * The feature id for the '<em><b>Step Object Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEN__STEP_OBJECT_NAME = TEST_STEP__STEP_OBJECT_NAME;

  /**
   * The feature id for the '<em><b>Step Definition Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEN__STEP_DEFINITION_NAME = TEST_STEP__STEP_DEFINITION_NAME;

  /**
   * The feature id for the '<em><b>Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEN__TABLE = TEST_STEP__TABLE;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEN__TEXT = TEST_STEP__TEXT;

  /**
   * The number of structural features of the '<em>Then</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEN_FEATURE_COUNT = TEST_STEP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.AndImpl <em>And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AndImpl
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getAnd()
   * @generated
   */
  int AND = 13;

  /**
   * The feature id for the '<em><b>Step Object Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__STEP_OBJECT_NAME = TEST_STEP__STEP_OBJECT_NAME;

  /**
   * The feature id for the '<em><b>Step Definition Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__STEP_DEFINITION_NAME = TEST_STEP__STEP_DEFINITION_NAME;

  /**
   * The feature id for the '<em><b>Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__TABLE = TEST_STEP__TABLE;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__TEXT = TEST_STEP__TEXT;

  /**
   * The number of structural features of the '<em>And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FEATURE_COUNT = TEST_STEP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.TextImpl <em>Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.TextImpl
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getText()
   * @generated
   */
  int TEXT = 14;

  /**
   * The feature id for the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__CONTENT = 0;

  /**
   * The number of structural features of the '<em>Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.DescriptionImpl <em>Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.DescriptionImpl
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getDescription()
   * @generated
   */
  int DESCRIPTION = 15;

  /**
   * The feature id for the '<em><b>Line List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__LINE_LIST = 0;

  /**
   * The number of structural features of the '<em>Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.TableImpl <em>Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.TableImpl
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getTable()
   * @generated
   */
  int TABLE = 16;

  /**
   * The feature id for the '<em><b>Row List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__ROW_LIST = 0;

  /**
   * The number of structural features of the '<em>Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.RowImpl <em>Row</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.RowImpl
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getRow()
   * @generated
   */
  int ROW = 17;

  /**
   * The feature id for the '<em><b>Cell List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW__CELL_LIST = 0;

  /**
   * The number of structural features of the '<em>Row</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.CellImpl <em>Cell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.CellImpl
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getCell()
   * @generated
   */
  int CELL = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__NAME = 0;

  /**
   * The number of structural features of the '<em>Cell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.LineImpl <em>Line</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.LineImpl
   * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getLine()
   * @generated
   */
  int LINE = 19;

  /**
   * The feature id for the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE__CONTENT = 0;

  /**
   * The number of structural features of the '<em>Line</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.farhan.dsl.asciidoc.asciiDoc.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.dsl.asciidoc.asciiDoc.Model#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.Model#getName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.farhan.dsl.asciidoc.asciiDoc.Model#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.Model#getDescription()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Description();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.asciidoc.asciiDoc.StepObject <em>Step Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Step Object</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.StepObject
   * @generated
   */
  EClass getStepObject();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.asciidoc.asciiDoc.StepObject#getStepDefinitionList <em>Step Definition List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Step Definition List</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.StepObject#getStepDefinitionList()
   * @see #getStepObject()
   * @generated
   */
  EReference getStepObject_StepDefinitionList();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.asciidoc.asciiDoc.StepDefinition <em>Step Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Step Definition</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.StepDefinition
   * @generated
   */
  EClass getStepDefinition();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.dsl.asciidoc.asciiDoc.StepDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.StepDefinition#getName()
   * @see #getStepDefinition()
   * @generated
   */
  EAttribute getStepDefinition_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.farhan.dsl.asciidoc.asciiDoc.StepDefinition#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.StepDefinition#getDescription()
   * @see #getStepDefinition()
   * @generated
   */
  EReference getStepDefinition_Description();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.asciidoc.asciiDoc.StepDefinition#getStepParameterList <em>Step Parameter List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Step Parameter List</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.StepDefinition#getStepParameterList()
   * @see #getStepDefinition()
   * @generated
   */
  EReference getStepDefinition_StepParameterList();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.asciidoc.asciiDoc.StepParameters <em>Step Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Step Parameters</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.StepParameters
   * @generated
   */
  EClass getStepParameters();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.dsl.asciidoc.asciiDoc.StepParameters#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.StepParameters#getName()
   * @see #getStepParameters()
   * @generated
   */
  EAttribute getStepParameters_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.farhan.dsl.asciidoc.asciiDoc.StepParameters#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.StepParameters#getDescription()
   * @see #getStepParameters()
   * @generated
   */
  EReference getStepParameters_Description();

  /**
   * Returns the meta object for the containment reference '{@link org.farhan.dsl.asciidoc.asciiDoc.StepParameters#getTable <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Table</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.StepParameters#getTable()
   * @see #getStepParameters()
   * @generated
   */
  EReference getStepParameters_Table();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.asciidoc.asciiDoc.TestSuite <em>Test Suite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test Suite</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.TestSuite
   * @generated
   */
  EClass getTestSuite();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.asciidoc.asciiDoc.TestSuite#getTestStepContainerList <em>Test Step Container List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Test Step Container List</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.TestSuite#getTestStepContainerList()
   * @see #getTestSuite()
   * @generated
   */
  EReference getTestSuite_TestStepContainerList();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.asciidoc.asciiDoc.TestStepContainer <em>Test Step Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test Step Container</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.TestStepContainer
   * @generated
   */
  EClass getTestStepContainer();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.dsl.asciidoc.asciiDoc.TestStepContainer#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.TestStepContainer#getName()
   * @see #getTestStepContainer()
   * @generated
   */
  EAttribute getTestStepContainer_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.farhan.dsl.asciidoc.asciiDoc.TestStepContainer#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.TestStepContainer#getDescription()
   * @see #getTestStepContainer()
   * @generated
   */
  EReference getTestStepContainer_Description();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.asciidoc.asciiDoc.TestStepContainer#getTestStepList <em>Test Step List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Test Step List</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.TestStepContainer#getTestStepList()
   * @see #getTestStepContainer()
   * @generated
   */
  EReference getTestStepContainer_TestStepList();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.asciidoc.asciiDoc.TestSetup <em>Test Setup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test Setup</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.TestSetup
   * @generated
   */
  EClass getTestSetup();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.asciidoc.asciiDoc.TestCase <em>Test Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test Case</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.TestCase
   * @generated
   */
  EClass getTestCase();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.asciidoc.asciiDoc.TestCase#getTestDataList <em>Test Data List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Test Data List</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.TestCase#getTestDataList()
   * @see #getTestCase()
   * @generated
   */
  EReference getTestCase_TestDataList();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.asciidoc.asciiDoc.TestData <em>Test Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test Data</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.TestData
   * @generated
   */
  EClass getTestData();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.dsl.asciidoc.asciiDoc.TestData#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.TestData#getName()
   * @see #getTestData()
   * @generated
   */
  EAttribute getTestData_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.farhan.dsl.asciidoc.asciiDoc.TestData#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.TestData#getDescription()
   * @see #getTestData()
   * @generated
   */
  EReference getTestData_Description();

  /**
   * Returns the meta object for the containment reference '{@link org.farhan.dsl.asciidoc.asciiDoc.TestData#getTable <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Table</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.TestData#getTable()
   * @see #getTestData()
   * @generated
   */
  EReference getTestData_Table();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.asciidoc.asciiDoc.TestStep <em>Test Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test Step</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.TestStep
   * @generated
   */
  EClass getTestStep();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.dsl.asciidoc.asciiDoc.TestStep#getStepObjectName <em>Step Object Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Step Object Name</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.TestStep#getStepObjectName()
   * @see #getTestStep()
   * @generated
   */
  EAttribute getTestStep_StepObjectName();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.dsl.asciidoc.asciiDoc.TestStep#getStepDefinitionName <em>Step Definition Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Step Definition Name</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.TestStep#getStepDefinitionName()
   * @see #getTestStep()
   * @generated
   */
  EAttribute getTestStep_StepDefinitionName();

  /**
   * Returns the meta object for the containment reference '{@link org.farhan.dsl.asciidoc.asciiDoc.TestStep#getTable <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Table</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.TestStep#getTable()
   * @see #getTestStep()
   * @generated
   */
  EReference getTestStep_Table();

  /**
   * Returns the meta object for the containment reference '{@link org.farhan.dsl.asciidoc.asciiDoc.TestStep#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.TestStep#getText()
   * @see #getTestStep()
   * @generated
   */
  EReference getTestStep_Text();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.asciidoc.asciiDoc.Given <em>Given</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Given</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.Given
   * @generated
   */
  EClass getGiven();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.asciidoc.asciiDoc.When <em>When</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>When</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.When
   * @generated
   */
  EClass getWhen();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.asciidoc.asciiDoc.Then <em>Then</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Then</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.Then
   * @generated
   */
  EClass getThen();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.asciidoc.asciiDoc.And <em>And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.And
   * @generated
   */
  EClass getAnd();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.asciidoc.asciiDoc.Text <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.Text
   * @generated
   */
  EClass getText();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.dsl.asciidoc.asciiDoc.Text#getContent <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Content</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.Text#getContent()
   * @see #getText()
   * @generated
   */
  EAttribute getText_Content();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.asciidoc.asciiDoc.Description <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Description</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.Description
   * @generated
   */
  EClass getDescription();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.asciidoc.asciiDoc.Description#getLineList <em>Line List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Line List</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.Description#getLineList()
   * @see #getDescription()
   * @generated
   */
  EReference getDescription_LineList();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.asciidoc.asciiDoc.Table <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.Table
   * @generated
   */
  EClass getTable();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.asciidoc.asciiDoc.Table#getRowList <em>Row List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Row List</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.Table#getRowList()
   * @see #getTable()
   * @generated
   */
  EReference getTable_RowList();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.asciidoc.asciiDoc.Row <em>Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Row</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.Row
   * @generated
   */
  EClass getRow();

  /**
   * Returns the meta object for the containment reference list '{@link org.farhan.dsl.asciidoc.asciiDoc.Row#getCellList <em>Cell List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cell List</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.Row#getCellList()
   * @see #getRow()
   * @generated
   */
  EReference getRow_CellList();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.asciidoc.asciiDoc.Cell <em>Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cell</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.Cell
   * @generated
   */
  EClass getCell();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.dsl.asciidoc.asciiDoc.Cell#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.Cell#getName()
   * @see #getCell()
   * @generated
   */
  EAttribute getCell_Name();

  /**
   * Returns the meta object for class '{@link org.farhan.dsl.asciidoc.asciiDoc.Line <em>Line</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Line</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.Line
   * @generated
   */
  EClass getLine();

  /**
   * Returns the meta object for the attribute '{@link org.farhan.dsl.asciidoc.asciiDoc.Line#getContent <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Content</em>'.
   * @see org.farhan.dsl.asciidoc.asciiDoc.Line#getContent()
   * @see #getLine()
   * @generated
   */
  EAttribute getLine_Content();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AsciiDocFactory getAsciiDocFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.ModelImpl
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__NAME = eINSTANCE.getModel_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__DESCRIPTION = eINSTANCE.getModel_Description();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.StepObjectImpl <em>Step Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.StepObjectImpl
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getStepObject()
     * @generated
     */
    EClass STEP_OBJECT = eINSTANCE.getStepObject();

    /**
     * The meta object literal for the '<em><b>Step Definition List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP_OBJECT__STEP_DEFINITION_LIST = eINSTANCE.getStepObject_StepDefinitionList();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.StepDefinitionImpl <em>Step Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.StepDefinitionImpl
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getStepDefinition()
     * @generated
     */
    EClass STEP_DEFINITION = eINSTANCE.getStepDefinition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STEP_DEFINITION__NAME = eINSTANCE.getStepDefinition_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP_DEFINITION__DESCRIPTION = eINSTANCE.getStepDefinition_Description();

    /**
     * The meta object literal for the '<em><b>Step Parameter List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP_DEFINITION__STEP_PARAMETER_LIST = eINSTANCE.getStepDefinition_StepParameterList();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.StepParametersImpl <em>Step Parameters</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.StepParametersImpl
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getStepParameters()
     * @generated
     */
    EClass STEP_PARAMETERS = eINSTANCE.getStepParameters();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STEP_PARAMETERS__NAME = eINSTANCE.getStepParameters_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP_PARAMETERS__DESCRIPTION = eINSTANCE.getStepParameters_Description();

    /**
     * The meta object literal for the '<em><b>Table</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP_PARAMETERS__TABLE = eINSTANCE.getStepParameters_Table();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.TestSuiteImpl <em>Test Suite</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.TestSuiteImpl
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getTestSuite()
     * @generated
     */
    EClass TEST_SUITE = eINSTANCE.getTestSuite();

    /**
     * The meta object literal for the '<em><b>Test Step Container List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_SUITE__TEST_STEP_CONTAINER_LIST = eINSTANCE.getTestSuite_TestStepContainerList();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.TestStepContainerImpl <em>Test Step Container</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.TestStepContainerImpl
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getTestStepContainer()
     * @generated
     */
    EClass TEST_STEP_CONTAINER = eINSTANCE.getTestStepContainer();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST_STEP_CONTAINER__NAME = eINSTANCE.getTestStepContainer_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_STEP_CONTAINER__DESCRIPTION = eINSTANCE.getTestStepContainer_Description();

    /**
     * The meta object literal for the '<em><b>Test Step List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_STEP_CONTAINER__TEST_STEP_LIST = eINSTANCE.getTestStepContainer_TestStepList();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.TestSetupImpl <em>Test Setup</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.TestSetupImpl
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getTestSetup()
     * @generated
     */
    EClass TEST_SETUP = eINSTANCE.getTestSetup();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.TestCaseImpl <em>Test Case</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.TestCaseImpl
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getTestCase()
     * @generated
     */
    EClass TEST_CASE = eINSTANCE.getTestCase();

    /**
     * The meta object literal for the '<em><b>Test Data List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_CASE__TEST_DATA_LIST = eINSTANCE.getTestCase_TestDataList();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.TestDataImpl <em>Test Data</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.TestDataImpl
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getTestData()
     * @generated
     */
    EClass TEST_DATA = eINSTANCE.getTestData();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST_DATA__NAME = eINSTANCE.getTestData_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_DATA__DESCRIPTION = eINSTANCE.getTestData_Description();

    /**
     * The meta object literal for the '<em><b>Table</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_DATA__TABLE = eINSTANCE.getTestData_Table();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.TestStepImpl <em>Test Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.TestStepImpl
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getTestStep()
     * @generated
     */
    EClass TEST_STEP = eINSTANCE.getTestStep();

    /**
     * The meta object literal for the '<em><b>Step Object Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST_STEP__STEP_OBJECT_NAME = eINSTANCE.getTestStep_StepObjectName();

    /**
     * The meta object literal for the '<em><b>Step Definition Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST_STEP__STEP_DEFINITION_NAME = eINSTANCE.getTestStep_StepDefinitionName();

    /**
     * The meta object literal for the '<em><b>Table</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_STEP__TABLE = eINSTANCE.getTestStep_Table();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_STEP__TEXT = eINSTANCE.getTestStep_Text();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.GivenImpl <em>Given</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.GivenImpl
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getGiven()
     * @generated
     */
    EClass GIVEN = eINSTANCE.getGiven();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.WhenImpl <em>When</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.WhenImpl
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getWhen()
     * @generated
     */
    EClass WHEN = eINSTANCE.getWhen();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.ThenImpl <em>Then</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.ThenImpl
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getThen()
     * @generated
     */
    EClass THEN = eINSTANCE.getThen();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.AndImpl <em>And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AndImpl
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getAnd()
     * @generated
     */
    EClass AND = eINSTANCE.getAnd();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.TextImpl <em>Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.TextImpl
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getText()
     * @generated
     */
    EClass TEXT = eINSTANCE.getText();

    /**
     * The meta object literal for the '<em><b>Content</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT__CONTENT = eINSTANCE.getText_Content();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.DescriptionImpl <em>Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.DescriptionImpl
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getDescription()
     * @generated
     */
    EClass DESCRIPTION = eINSTANCE.getDescription();

    /**
     * The meta object literal for the '<em><b>Line List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DESCRIPTION__LINE_LIST = eINSTANCE.getDescription_LineList();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.TableImpl <em>Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.TableImpl
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getTable()
     * @generated
     */
    EClass TABLE = eINSTANCE.getTable();

    /**
     * The meta object literal for the '<em><b>Row List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE__ROW_LIST = eINSTANCE.getTable_RowList();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.RowImpl <em>Row</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.RowImpl
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getRow()
     * @generated
     */
    EClass ROW = eINSTANCE.getRow();

    /**
     * The meta object literal for the '<em><b>Cell List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW__CELL_LIST = eINSTANCE.getRow_CellList();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.CellImpl <em>Cell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.CellImpl
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getCell()
     * @generated
     */
    EClass CELL = eINSTANCE.getCell();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELL__NAME = eINSTANCE.getCell_Name();

    /**
     * The meta object literal for the '{@link org.farhan.dsl.asciidoc.asciiDoc.impl.LineImpl <em>Line</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.LineImpl
     * @see org.farhan.dsl.asciidoc.asciiDoc.impl.AsciiDocPackageImpl#getLine()
     * @generated
     */
    EClass LINE = eINSTANCE.getLine();

    /**
     * The meta object literal for the '<em><b>Content</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINE__CONTENT = eINSTANCE.getLine_Content();

  }

} //AsciiDocPackage
