/**
 * generated by Xtext 2.40.0
 */
package org.farhan.dsl.asciidoc.asciiDoc;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Given</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.farhan.dsl.asciidoc.asciiDoc.AsciiDocPackage#getGiven()
 * @model
 * @generated
 */
public interface Given extends TestStep
{
} // Given
