/**
 * generated by Xtext 2.40.0
 */
package org.farhan.dsl.asciidoc.asciiDoc;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Row</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.farhan.dsl.asciidoc.asciiDoc.Row#getCellList <em>Cell List</em>}</li>
 * </ul>
 *
 * @see org.farhan.dsl.asciidoc.asciiDoc.AsciiDocPackage#getRow()
 * @model
 * @generated
 */
public interface Row extends EObject
{
  /**
   * Returns the value of the '<em><b>Cell List</b></em>' containment reference list.
   * The list contents are of type {@link org.farhan.dsl.asciidoc.asciiDoc.Cell}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cell List</em>' containment reference list.
   * @see org.farhan.dsl.asciidoc.asciiDoc.AsciiDocPackage#getRow_CellList()
   * @model containment="true"
   * @generated
   */
  EList<Cell> getCellList();

} // Row
