/**
 * generated by Xtext 2.40.0
 */
package org.farhan.dsl.asciidoc.asciiDoc;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Step Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.farhan.dsl.asciidoc.asciiDoc.StepObject#getStepDefinitionList <em>Step Definition List</em>}</li>
 * </ul>
 *
 * @see org.farhan.dsl.asciidoc.asciiDoc.AsciiDocPackage#getStepObject()
 * @model
 * @generated
 */
public interface StepObject extends Model
{
  /**
   * Returns the value of the '<em><b>Step Definition List</b></em>' containment reference list.
   * The list contents are of type {@link org.farhan.dsl.asciidoc.asciiDoc.StepDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Step Definition List</em>' containment reference list.
   * @see org.farhan.dsl.asciidoc.asciiDoc.AsciiDocPackage#getStepObject_StepDefinitionList()
   * @model containment="true"
   * @generated
   */
  EList<StepDefinition> getStepDefinitionList();

} // StepObject
