/**
 * generated by Xtext 2.40.0
 */
package org.farhan.dsl.asciidoc.asciiDoc;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Test Suite</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.farhan.dsl.asciidoc.asciiDoc.TestSuite#getTestStepContainerList <em>Test Step Container List</em>}</li>
 * </ul>
 *
 * @see org.farhan.dsl.asciidoc.asciiDoc.AsciiDocPackage#getTestSuite()
 * @model
 * @generated
 */
public interface TestSuite extends Model
{
  /**
   * Returns the value of the '<em><b>Test Step Container List</b></em>' containment reference list.
   * The list contents are of type {@link org.farhan.dsl.asciidoc.asciiDoc.TestStepContainer}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Test Step Container List</em>' containment reference list.
   * @see org.farhan.dsl.asciidoc.asciiDoc.AsciiDocPackage#getTestSuite_TestStepContainerList()
   * @model containment="true"
   * @generated
   */
  EList<TestStepContainer> getTestStepContainerList();

} // TestSuite
