/*
 * generated by Xtext 2.39.0
 */
package org.farhan.dsl.asciidoc.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.farhan.dsl.asciidoc.AsciiDocRuntimeModule;
import org.farhan.dsl.asciidoc.AsciiDocStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AsciiDocIdeSetup extends AsciiDocStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AsciiDocRuntimeModule(), new AsciiDocIdeModule()));
	}
	
}
