/*
 * generated by Xtext 2.36.0
 */
package org.farhan.dsl.asciidoc.ide.quickfix;

import org.eclipse.xtext.ide.editor.quickfix.AbstractDeclarativeIdeQuickfixProvider;
/**
 * Custom quickfixes.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
public class AsciiDocIdeQuickfixProvider extends AbstractDeclarativeIdeQuickfixProvider {

}
