/*
 * generated by Xtext 2.36.0
 */
package org.farhan.dsl.asciidoc.formatting2;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.formatting2.AbstractJavaFormatter;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.formatting2.regionaccess.ISemanticRegion;
import org.farhan.dsl.asciidoc.services.AsciiDocGrammarAccess;
import org.farhan.dsl.asciidoc.asciiDoc.TestSuite;
import org.farhan.dsl.asciidoc.asciiDoc.StepObject;

import com.google.inject.Inject;

public class AsciiDocFormatter extends AbstractJavaFormatter {

	@Inject
	AsciiDocGrammarAccess ga;

	protected void format(TestSuite theFeature, IFormattableDocument doc) {

		TestSuiteFormatter formatter = new TestSuiteFormatter(theFeature);
		formatter.setIndent(0);
		formatter.format(doc, ga, this);
	}

	protected void format(StepObject theStepObject, IFormattableDocument doc) {

		StepObjectFormatter formatter = new StepObjectFormatter(theStepObject);
		formatter.setIndent(0);
		formatter.format(doc, ga, this);
	}

	public ISemanticRegion getRegion(EObject eo, RuleCall ruleCall) {
		return regionFor(eo).ruleCall(ruleCall);
	}

	public ISemanticRegion getRegion(EObject eo, Keyword keyword) {
		// You can also search for the keyword using keyword("Feature:");
		return regionFor(eo).keyword(keyword);
	}

	public ISemanticRegion getRegion(EObject eo, Assignment assignment) {
		return regionFor(eo).assignment(assignment);
	}
}
