/*
 * generated by Xtext 2.39.0
 */
package org.farhan.dsl.asciidoc.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class AsciiDocScopeProvider extends AbstractAsciiDocScopeProvider {

}
