/*
 * generated by Xtext 2.40.0
 */
package org.farhan.dsl.asciidoc.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractAsciiDocValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.farhan.dsl.asciidoc.asciiDoc.AsciiDocPackage.eINSTANCE);
		return result;
	}
}
