apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheep-dog-cucumber-gen-svc
  labels:
    app: sheep-dog
    component: sheep-dog-cucumber-gen-svc
spec:
  selector:
    matchLabels:
      component: sheep-dog-cucumber-gen-svc
  template:
    metadata:
      labels:
        app: sheep-dog
        component: sheep-dog-cucumber-gen-svc
    spec:
      containers:
        - name: sheep-dog-cucumber-gen-svc
          image: ghcr.io/farhan5248/sheep-dog-cucumber-gen-svc:latest
          imagePullPolicy: "Always"
          env:
            - name: JAVA_OPTS
              value: "-Xmx3g -Xms1g"
            - name: LOG_LEVEL
              value: "INFO"
            - name: LOG_PATH
              value: "/logs"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://sheep-dog-db:3306/mbt
            - name: SPRING_ARTEMIS_HOST
              value: sheep-dog-amq
            - name: SPRING_ARTEMIS_PORT
              value: "61616"
            - name: SPRING_ARTEMIS_USER
              value: artemis
            - name: SPRING_ARTEMIS_PASSWORD
              value: artemis
            - name: SHEEPDOG_HOST
              value: sheep-dog-asciidoc-api-svc
            - name: SHEEPDOG_PORT
              value: "80"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /sheep-dog-cucumber-gen-svc/actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: logs-volume
              mountPath: /logs
          resources:
            limits:
              memory: "4Gi"
              cpu: "500m"
            requests:
              memory: "2Gi"
              cpu: "250m"
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: sheep-dog-cucumber-gen-svc-pvc
