/*
 * generated by Xtext 2.36.0
 */
package org.farhan.dsl.asciidoc.tests;

import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(AsciiDocInjectorProvider.class)
public class AsciiDocParsingTest {
	@Test
	public void loadModel() throws Exception {
	}
}
