/*
 * generated by Xtext 2.39.0
 */
package org.farhan.dsl.asciidoc;

import org.eclipse.xtext.generator.IOutputConfigurationProvider;
import org.eclipse.xtext.parser.IParser;
import org.eclipse.xtext.parser.antlr.Lexer;
import org.eclipse.xtext.parser.antlr.LexerBindings;
import org.eclipse.xtext.parser.antlr.LexerProvider;
import org.farhan.dsl.grammar.SheepDogFactory;
import org.farhan.dsl.asciidoc.parser.antlr.CustomAsciiDocParser;
import org.farhan.dsl.asciidoc.parser.antlr.internal.InternalAsciiDocLexer;
import org.farhan.dsl.asciidoc.parser.antlr.internal.AsciiDocLexer;
import org.farhan.dsl.asciidoc.generator.AsciiDocOutputConfigurationProvider;
import org.farhan.dsl.asciidoc.impl.AsciiDocFactoryImpl;
import org.farhan.dsl.asciidoc.impl.VsCodeFileRepository;

import com.google.inject.Binder;
import com.google.inject.Provider;
import com.google.inject.Singleton;
import com.google.inject.name.Names;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class AsciiDocRuntimeModule extends AbstractAsciiDocRuntimeModule {

	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		binder.bind(IOutputConfigurationProvider.class).to(AsciiDocOutputConfigurationProvider.class)
				.in(Singleton.class);
		SheepDogFactory.instance = new AsciiDocFactoryImpl(new VsCodeFileRepository());
	}

	@Override
	public Class<? extends IParser> bindIParser() {
		return CustomAsciiDocParser.class;
	}

	@Override
	public Class<? extends Lexer> bindLexer() {
		return AsciiDocLexer.class;
	}

	@Override
	public Provider<? extends InternalAsciiDocLexer> provideInternalAsciiDocLexer() {
		return LexerProvider.create(AsciiDocLexer.class);
	}

	@Override
	public void configureRuntimeLexer(Binder binder) {
		binder.bind(Lexer.class).annotatedWith(Names.named(LexerBindings.RUNTIME)).to(AsciiDocLexer.class);
	}
}
