/*
 * generated by Xtext 2.39.0
 */
package org.farhan.dsl.asciidoc;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AsciiDocStandaloneSetup extends AsciiDocStandaloneSetupGenerated {

	public static void doSetup() {
		new AsciiDocStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
