/*
 * generated by Xtext 2.40.0
 */
package org.farhan.dsl.asciidoc.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.farhan.dsl.asciidoc.ide.contentassist.antlr.internal.InternalAsciiDocParser;
import org.farhan.dsl.asciidoc.services.AsciiDocGrammarAccess;

public class AsciiDocParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(AsciiDocGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, AsciiDocGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getModelAccess().getAlternatives(), "rule__Model__Alternatives");
			builder.put(grammarAccess.getTestStepContainerAccess().getAlternatives(), "rule__TestStepContainer__Alternatives");
			builder.put(grammarAccess.getTestStepAccess().getAlternatives(), "rule__TestStep__Alternatives");
			builder.put(grammarAccess.getStepObjectRefAccess().getAlternatives_1(), "rule__StepObjectRef__Alternatives_1");
			builder.put(grammarAccess.getStepObjectAccess().getGroup(), "rule__StepObject__Group__0");
			builder.put(grammarAccess.getStepDefinitionAccess().getGroup(), "rule__StepDefinition__Group__0");
			builder.put(grammarAccess.getStepParametersAccess().getGroup(), "rule__StepParameters__Group__0");
			builder.put(grammarAccess.getTestSuiteAccess().getGroup(), "rule__TestSuite__Group__0");
			builder.put(grammarAccess.getTestSetupAccess().getGroup(), "rule__TestSetup__Group__0");
			builder.put(grammarAccess.getTestCaseAccess().getGroup(), "rule__TestCase__Group__0");
			builder.put(grammarAccess.getTestDataAccess().getGroup(), "rule__TestData__Group__0");
			builder.put(grammarAccess.getGivenAccess().getGroup(), "rule__Given__Group__0");
			builder.put(grammarAccess.getWhenAccess().getGroup(), "rule__When__Group__0");
			builder.put(grammarAccess.getThenAccess().getGroup(), "rule__Then__Group__0");
			builder.put(grammarAccess.getAndAccess().getGroup(), "rule__And__Group__0");
			builder.put(grammarAccess.getTextAccess().getGroup(), "rule__Text__Group__0");
			builder.put(grammarAccess.getTableAccess().getGroup(), "rule__Table__Group__0");
			builder.put(grammarAccess.getRowAccess().getGroup(), "rule__Row__Group__0");
			builder.put(grammarAccess.getCellAccess().getGroup(), "rule__Cell__Group__0");
			builder.put(grammarAccess.getLineAccess().getGroup(), "rule__Line__Group__0");
			builder.put(grammarAccess.getStepObjectRefAccess().getGroup(), "rule__StepObjectRef__Group__0");
			builder.put(grammarAccess.getStepObjectAccess().getNameAssignment_2(), "rule__StepObject__NameAssignment_2");
			builder.put(grammarAccess.getStepObjectAccess().getDescriptionAssignment_4(), "rule__StepObject__DescriptionAssignment_4");
			builder.put(grammarAccess.getStepObjectAccess().getStepDefinitionListAssignment_5(), "rule__StepObject__StepDefinitionListAssignment_5");
			builder.put(grammarAccess.getStepDefinitionAccess().getNameAssignment_2(), "rule__StepDefinition__NameAssignment_2");
			builder.put(grammarAccess.getStepDefinitionAccess().getDescriptionAssignment_4(), "rule__StepDefinition__DescriptionAssignment_4");
			builder.put(grammarAccess.getStepDefinitionAccess().getStepParameterListAssignment_5(), "rule__StepDefinition__StepParameterListAssignment_5");
			builder.put(grammarAccess.getStepParametersAccess().getNameAssignment_2(), "rule__StepParameters__NameAssignment_2");
			builder.put(grammarAccess.getStepParametersAccess().getDescriptionAssignment_4(), "rule__StepParameters__DescriptionAssignment_4");
			builder.put(grammarAccess.getStepParametersAccess().getTableAssignment_5(), "rule__StepParameters__TableAssignment_5");
			builder.put(grammarAccess.getTestSuiteAccess().getNameAssignment_2(), "rule__TestSuite__NameAssignment_2");
			builder.put(grammarAccess.getTestSuiteAccess().getDescriptionAssignment_4(), "rule__TestSuite__DescriptionAssignment_4");
			builder.put(grammarAccess.getTestSuiteAccess().getTestStepContainerListAssignment_5(), "rule__TestSuite__TestStepContainerListAssignment_5");
			builder.put(grammarAccess.getTestSetupAccess().getNameAssignment_2(), "rule__TestSetup__NameAssignment_2");
			builder.put(grammarAccess.getTestSetupAccess().getDescriptionAssignment_4(), "rule__TestSetup__DescriptionAssignment_4");
			builder.put(grammarAccess.getTestSetupAccess().getTestStepListAssignment_5(), "rule__TestSetup__TestStepListAssignment_5");
			builder.put(grammarAccess.getTestCaseAccess().getNameAssignment_2(), "rule__TestCase__NameAssignment_2");
			builder.put(grammarAccess.getTestCaseAccess().getDescriptionAssignment_4(), "rule__TestCase__DescriptionAssignment_4");
			builder.put(grammarAccess.getTestCaseAccess().getTestStepListAssignment_5(), "rule__TestCase__TestStepListAssignment_5");
			builder.put(grammarAccess.getTestCaseAccess().getTestDataListAssignment_6(), "rule__TestCase__TestDataListAssignment_6");
			builder.put(grammarAccess.getTestDataAccess().getNameAssignment_2(), "rule__TestData__NameAssignment_2");
			builder.put(grammarAccess.getTestDataAccess().getDescriptionAssignment_4(), "rule__TestData__DescriptionAssignment_4");
			builder.put(grammarAccess.getTestDataAccess().getTableAssignment_5(), "rule__TestData__TableAssignment_5");
			builder.put(grammarAccess.getGivenAccess().getStepObjectNameAssignment_2(), "rule__Given__StepObjectNameAssignment_2");
			builder.put(grammarAccess.getGivenAccess().getStepDefinitionNameAssignment_3(), "rule__Given__StepDefinitionNameAssignment_3");
			builder.put(grammarAccess.getGivenAccess().getTableAssignment_5(), "rule__Given__TableAssignment_5");
			builder.put(grammarAccess.getGivenAccess().getTextAssignment_6(), "rule__Given__TextAssignment_6");
			builder.put(grammarAccess.getWhenAccess().getStepObjectNameAssignment_2(), "rule__When__StepObjectNameAssignment_2");
			builder.put(grammarAccess.getWhenAccess().getStepDefinitionNameAssignment_3(), "rule__When__StepDefinitionNameAssignment_3");
			builder.put(grammarAccess.getWhenAccess().getTableAssignment_5(), "rule__When__TableAssignment_5");
			builder.put(grammarAccess.getWhenAccess().getTextAssignment_6(), "rule__When__TextAssignment_6");
			builder.put(grammarAccess.getThenAccess().getStepObjectNameAssignment_2(), "rule__Then__StepObjectNameAssignment_2");
			builder.put(grammarAccess.getThenAccess().getStepDefinitionNameAssignment_3(), "rule__Then__StepDefinitionNameAssignment_3");
			builder.put(grammarAccess.getThenAccess().getTableAssignment_5(), "rule__Then__TableAssignment_5");
			builder.put(grammarAccess.getThenAccess().getTextAssignment_6(), "rule__Then__TextAssignment_6");
			builder.put(grammarAccess.getAndAccess().getStepObjectNameAssignment_2(), "rule__And__StepObjectNameAssignment_2");
			builder.put(grammarAccess.getAndAccess().getStepDefinitionNameAssignment_3(), "rule__And__StepDefinitionNameAssignment_3");
			builder.put(grammarAccess.getAndAccess().getTableAssignment_5(), "rule__And__TableAssignment_5");
			builder.put(grammarAccess.getAndAccess().getTextAssignment_6(), "rule__And__TextAssignment_6");
			builder.put(grammarAccess.getTextAccess().getContentAssignment_0(), "rule__Text__ContentAssignment_0");
			builder.put(grammarAccess.getDescriptionAccess().getLineListAssignment(), "rule__Description__LineListAssignment");
			builder.put(grammarAccess.getTableAccess().getRowListAssignment_2(), "rule__Table__RowListAssignment_2");
			builder.put(grammarAccess.getRowAccess().getCellListAssignment_0(), "rule__Row__CellListAssignment_0");
			builder.put(grammarAccess.getCellAccess().getNameAssignment_1(), "rule__Cell__NameAssignment_1");
			builder.put(grammarAccess.getLineAccess().getContentAssignment_0(), "rule__Line__ContentAssignment_0");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private AsciiDocGrammarAccess grammarAccess;

	@Override
	protected InternalAsciiDocParser createParser() {
		InternalAsciiDocParser result = new InternalAsciiDocParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_SL_COMMENT" };
	}

	public AsciiDocGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AsciiDocGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
