name: Publish Sheep Dog MCP Svc Release

on:
  workflow_dispatch:
permissions:
  contents: write
  packages: write

jobs:
  sheep-dog-mcp-svc:
    uses: farhan5248/sheep-dog-ops/.github/workflows/release-maven.yml@main
    with:
      project: 'sheep-dog-mcp-svc'
    secrets: inherit

  merge-into-develop:
    needs: [sheep-dog-mcp-svc]
    uses: farhan5248/sheep-dog-ops/.github/workflows/merge.yml@main
    with:
      source: 'main'
      target: 'develop'
    secrets: inherit
