name: Publish Sheep Dog Cloud Snapshot

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - '.github/**'
      - '**/kubernetes/**'
      - '**/docker/**'
      - '**/src/**'
      - '**/pom.xml'
permissions:
  contents: write
  packages: write

jobs:
  sheep-dog-asciidoc-api-svc:
    uses: farhan5248/sheep-dog-ops/.github/workflows/snapshot-docker.yml@main
    with:
      project: 'sheep-dog-asciidoc-api-svc'
    secrets: inherit

  sheep-dog-dev-svc:
    needs: [sheep-dog-asciidoc-api-svc]
    uses: farhan5248/sheep-dog-ops/.github/workflows/snapshot-docker.yml@main
    with:
      project: 'sheep-dog-dev-svc'
    secrets: inherit

  sheep-dog-dev-mcp:
    needs: [sheep-dog-dev-svc]
    uses: farhan5248/sheep-dog-ops/.github/workflows/snapshot-docker.yml@main
    with:
      project: 'sheep-dog-dev-mcp'
    secrets: inherit

  sheep-dog-dev-svc-maven-plugin:
    needs: [sheep-dog-dev-svc]
    uses: farhan5248/sheep-dog-ops/.github/workflows/snapshot-docker.yml@main
    with:
      project: 'sheep-dog-dev-svc-maven-plugin'
    secrets: inherit

  darmok-maven-plugin:
    needs: [sheep-dog-dev-svc-maven-plugin]
    uses: farhan5248/sheep-dog-ops/.github/workflows/snapshot-docker.yml@main
    with:
      project: 'darmok-maven-plugin'
    secrets: inherit

  sheep-dog-vscode-plugin:
    uses: farhan5248/sheep-dog-ops/.github/workflows/snapshot-gradle.yml@main
    with:
      project: 'sheep-dog-vscode-plugin'
    secrets: inherit

  sheep-dog-eclipse-plugin:
    uses: farhan5248/sheep-dog-ops/.github/workflows/snapshot-maven.yml@main
    with:
      project: 'sheepdogeclipseplugin.parent'
    secrets: inherit

  merge-into-main:
    needs: [sheep-dog-asciidoc-api-svc, sheep-dog-dev-mcp, darmok-maven-plugin, sheep-dog-vscode-plugin, sheep-dog-eclipse-plugin]
    uses: farhan5248/sheep-dog-ops/.github/workflows/merge.yml@main
    with:
      source: 'main'
      target: 'develop'
    secrets: inherit
