name: Publish Sheep Dog Cucumber Gen Svc Release

on:
  workflow_dispatch:
concurrency:
  group: sheep-dog-svc
  cancel-in-progress: false
permissions:
  contents: write
  packages: write

jobs:
  sheep-dog-cucumber-gen-svc:
    uses: farhan5248/sheep-dog-ops/.github/workflows/release-maven.yml@main
    with:
      project: 'sheep-dog-cucumber-gen-svc'
    secrets: inherit

  sheep-dog-svc-maven-plugin:
    needs: [sheep-dog-cucumber-gen-svc]
    uses: farhan5248/sheep-dog-ops/.github/workflows/release-maven.yml@main
    with:
      project: 'sheep-dog-svc-maven-plugin'
    secrets: inherit

  darmok-maven-plugin:
    needs: [sheep-dog-svc-maven-plugin]
    uses: farhan5248/sheep-dog-ops/.github/workflows/release-maven.yml@main
    with:
      project: 'darmok-maven-plugin'
    secrets: inherit

  merge-into-develop:
    needs: [darmok-maven-plugin]
    uses: farhan5248/sheep-dog-ops/.github/workflows/merge.yml@main
    with:
      source: 'main'
      target: 'develop'
    secrets: inherit
