name: Publish SheepDog AsciiDoc Release
on:
  workflow_dispatch:
permissions:
  contents: write
  packages: write

jobs:
  sheepdog-asciidoc:
    uses: farhan5248/sheep-dog-ops/.github/workflows/gradle-release.yml@main
    with:
      project: 'sheepdogasciidoc.parent'
    secrets: inherit

  merge-into-develop:
    needs: [sheepdog-asciidoc]
    uses: farhan5248/sheep-dog-ops/.github/workflows/merge.yml@main
    with:
      source: 'main'
      target: 'develop'
    secrets: inherit
